theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:title/
title: Guizhen Wang
description: Passionate in data visualization, machine learning and computer science.
logo: /assets/img/IMG_logo.png
github.owner_name: Guizhen Wang
github.is_user_page: 1

