theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock

markdown: GFM
permalink: /:categories/:year/:month/:title/


title: Guizhen Wang
email: wang1908@purdue.edu
description: Passionate in data visualization, machine learning, statistics, and computer science techniques handling big data.
logo: /assets/images/logo2.png
github.owner_name: Guizhen Wang
github.is_user_page: 1
github.owner_url: https://github.com/guizhen-wang
sociallinks: 1
resume_url: 
linkedin_url: https://www.linkedin.com/in/guizhen-wang-magic
googlescholar_url: https://scholar.google.com/citations?user=vA6zplcAAAAJ&hl=en
