theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

markdown: GFM
permalink: /:categories/:year/:month/:title/

# layout: page
# title: "PAGE TITLE"
# permalink: /url/

title: Guizhen Wang
email: wang1908@purdue.edu
description: Passionate in data visualization, machine learning and computer science.
logo: /assets/img/IMG_logo.png
github.owner_name: Guizhen Wang
github.is_user_page: 1
github.owner_url: https://github.com/guizhen-wang
sociallinks: 1
resume_url: /assets/doc/resume.pdf
linkedin_url: https://www.linkedin.com/in/guizhen-wang-magic
# google_analytics: 1